// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnjaybUhmXMGnUzQ2dffSFhR9K0Fbb9o',
    appId: '1:384201046053:android:0a118c8f1eccf4d990e7cc',
    messagingSenderId: '384201046053',
    projectId: 'flutter-crud-7a01d',
    storageBucket: 'flutter-crud-7a01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Ua5s8l3yZXQNATfVVU3Q3LMkmADJ9V8',
    appId: '1:384201046053:ios:bb16f335ebdcffd690e7cc',
    messagingSenderId: '384201046053',
    projectId: 'flutter-crud-7a01d',
    storageBucket: 'flutter-crud-7a01d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Ua5s8l3yZXQNATfVVU3Q3LMkmADJ9V8',
    appId: '1:384201046053:ios:bb16f335ebdcffd690e7cc',
    messagingSenderId: '384201046053',
    projectId: 'flutter-crud-7a01d',
    storageBucket: 'flutter-crud-7a01d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseStudy',
  );

}